name: Update Agenda en Wedstrijdschema
on:
  schedule:
    - cron: "0 5 * * *" # Dagelijks om 05:00 UTC (06:00 NL tijd)
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run agenda scraper
        run: python scrape_agenda.py
      - name: Run wedstrijdschema scraper
        run: python scrape_wedstrijdschema.py
      - name: Upload screenshots as artifacts
        if: always() # Zorgt ervoor dat de screenshots worden geüpload, zelfs als de scrapers falen
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: |
            screenshot.png
            screenshot_wedstrijdschema.png
      - name: Deploy to GitHub Pages
        if: success() # Alleen uitvoeren als de scrapers succesvol zijn
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
